### ISSUE TITLE
Cant install via composer

### ISSUE THREAD

**Issue by mai1237** [JustSteveKing/laravel-erp#2]
In clear laravel installation ,Jetstream  , Livewire
when runnung 
composer require juststeveking/laravel-erp
I get the erron messaage below

  [InvalidArgumentException]
  Could not find package juststeveking/laravel-erp.

  Did you mean this?
      juststeveking/laravel-erp-contracts

**Comment by JustSteveKing** [comment]
Hey @mai1237 thanks for tryuing to use the package! However it has not been released as a package yet as it is no way near ready.

All we have so far is the module installer built - we are most likely around 6-8 weeks away from having a beta version ready to try.

**Comment by HazJ** [comment]
Hey @mai1237,
You can also follow the development process here:
https://www.youtube.com/watch?v=N-3febTppLs
Be sure to follow check [Larastreamers](https://larastreamers.com/) for upcoming streams.
